name: test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      - name: Test output
        run: |
          echo "before {{ github.before }}"
          echo "ref {{ github.ref }}"
          echo "ref^  {{ github.ref }}^"
          echo "sha {{ github.sha }}"
          echo "sha^  {{ github.sha }}^"
      - name: git diff before to sha
        run: git diff --name-only ${{ github.event.before }} ${{ github.sha }}
      - name: git diff sha^
        run: git diff --name-only ${{ github.sha }}^ ${{ github.sha }}
