name: test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - name: git diff
        run: git diff --name-only head^..head
